image: node:18-alpine
stages:
  - test
  - report-coverage

before_script:
  - yarn install --frozen-lockfile
  
unit-test-job:
  stage: test
  script:
    - yarn test
  rules:
    - if: ($CI_PIPELINE_SOURCE == 'merge_request_event' && ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "development" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main")) || $CI_COMMIT_BRANCH == "main"
      when: always
  coverage: '/All files[^|]*|[^|]*s+([d.]+)/'
  artifacts:
      when: always
      paths:
        - coverage/lcov-report
        - coverage/cobertura-coverage.xml
        - junit.xml
      reports:
        junit:
          - junit.xml
        coverage_report:
          coverage_format: cobertura
          path: coverage/cobertura-coverage.xml
lint-test-job:
  stage: test
  script:
    - yarn lint
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "development" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main")
      when: always
pages:
  stage: report-coverage
  dependencies:
    - unit-test-job
  script:
    - mv coverage/lcov-report/ public/
  artifacts:
    paths:
      - public/
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: always