image: node:18-alpine

pipelines:
  pull-requests:
    '{main,development}':
      - step:
          name: Yarn setup
          script:
            - yarn install --frozen-lockfile
      - parallel:
          - step:
              name: 'Lint Testing'
              script:
                - 'yarn lint'
          - step:
              name: 'Unit Testing'
              script:
                - 'yarn test'
