image: atlassian/default-image:3

pipelines:
  pull-requests:
    '{main,development}':
      - parallel:
          - step:
              name: 'Lint Testing'
              script:
                - 'yarn lint'
          - step:
              name: 'Unit Testing'
              script:
                - 'yarn test'
