image: node:18-alpine

pipelines:
  pull-requests:
    '{main,development}':
      - parallel:
          - step:
              name: 'Lint Testing'
              script:
                - yarn install --frozen-lockfile
                - 'yarn lint'
          - step:
              name: 'Unit Testing'
              script:
                - yarn install --frozen-lockfile
                - 'JEST_JUNIT_OUTPUT_DIR="test-reports" yarn test'

  branches:
    main:
      - step:
          name: 'Unit Testing'
          script:
            - yarn install --frozen-lockfile
            - 'yarn test'
