name: Tests on Pullrequests

on:
  pull_request:
    branches:
      - 'main'
      - 'development'

jobs:
  job-lint-test:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install Node modules
        run: yarn install --frozen-lockfile

      - name: Linting
        run: yarn lint

  job-unit-test:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install Node modules
        run: yarn install --frozen-lockfile

      - name: Unit & Integration tests
        run: yarn test

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure() # run this step even if previous step failed
        with:
          name: JEST Tests # Name of the check run which will be created
          path: ./junit.xml # Path to test results
          reporter: jest-junit
